# Generated by Django 5.1.2 on 2024-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('editable', 'Editable'), ('bloqueado', 'Bloqueado')], default='editable', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
