# Generated by Django 5.1.2 on 2024-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_venta_total_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado',
            field=models.CharField(choices=[('editable', 'Editable'), ('bloqueado', 'Bloqueado')], default='editable', max_length=10),
        ),
    ]
