# Generated by Django 5.0.6 on 2024-06-12 17:07

import builtins
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('Cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('Fecha_n', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('Direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('Sexo', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image_prod', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/&d')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.producto')),
                ('fk_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.venta')),
            ],
            options={
                'verbose_name': 'DetVenta',
                'verbose_name_plural': 'DetalleVentas',
                'db_table': 'DetVenta',
                'ordering': [builtins.id],
            },
        ),
    ]
