# Generated by Django 5.1 on 2024-08-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipios',
            old_name='departamento',
            new_name='departamento_id',
        ),
    ]
