# Generated by Django 5.1.1 on 2024-10-07 16:17

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_campos], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_emision',
            field=models.DateField(verbose_name='Fecha de emisión'),
        ),
    ]
