# Generated by Django 5.1.1 on 2024-09-16 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ['num_factura'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compras',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='impuestos',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='compras',
            name='num_factura',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio(Cop)'),
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA (%)')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'DetalleCompra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('iva', models.PositiveIntegerField(default=19, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'DetalleVenta',
            },
        ),
    ]
