# Generated by Django 5.0.8 on 2024-08-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cod_postal',
            new_name='ciudad',
        ),
    ]
