# Generated by Django 5.1.1 on 2024-09-12 10:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nombres',
            field=models.CharField(blank=True, max_length=30, validators=[app.models.validate_nombre], verbose_name='Nombres y apellidos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
