# Generated by Django 5.1.1 on 2024-09-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usurio', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_Usuarios',
            field=models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica')], default='PN', max_length=2, verbose_name='Tipo de Usuarios'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica')], default='PN', max_length=2, verbose_name='Tipo de Usuarios'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
