# Generated by Django 5.0.6 on 2024-06-21 13:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, unique=True, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'Tipo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=11, unique=True, verbose_name='Cedula')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('edad', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('categ', models.ManyToManyField(to='app.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
