# Generated by Django 5.0.8 on 2024-08-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cod_postal_cliente_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='cod_postal',
            new_name='ciudad',
        ),
    ]
