# Generated by Django 5.1.1 on 2024-09-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email_alter_customuser_nombres_and_more'),
        ('app', '0002_alter_venta_producto'),
    ]

    operations = [
    ]
