# Generated by Django 5.1.1 on 2024-09-09 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_persona_usuario_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='tipo_Usuarios',
            new_name='tipo_persona',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo', verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='precio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio(Cop)'),
        ),
    ]
