# Generated by Django 5.1.1 on 2024-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_venta_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
