# Generated by Django 5.1 on 2024-08-20 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_apellidos_remove_proveedor_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='El número de documento debe contener solo dígitos.', regex='^\\d+$')], verbose_name='Número de Documento'),
        ),
    ]
