# Generated by Django 5.1 on 2024-08-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_departamento_municipios_departamento_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipios',
            old_name='departamento_id',
            new_name='departamento',
        ),
    ]
