# Generated by Django 5.1.1 on 2024-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_compras_options_remove_compras_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='total',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
    ]
