# Generated by Django 5.1.1 on 2024-09-09 20:13

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tipo_usuarios_proveedor_tipo_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_campos], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='decreto',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_campos], verbose_name='Decreto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_campos], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_campos], verbose_name='Nombre'),
        ),
    ]
