# Generated by Django 5.1.1 on 2024-09-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detalleventa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='num_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
