# Generated by Django 5.0.8 on 2024-08-06 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_cod_postal_proveedor_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Numero de Documento'),
        ),
    ]
