# Generated by Django 5.1.1 on 2024-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoria_descripcion_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
