# Generated by Django 5.1.1 on 2024-09-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_detalleventa_num_factura_alter_detalleventa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_emision',
            field=models.DateTimeField(verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='num_factura',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
