# Generated by Django 5.1.1 on 2024-10-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tipo_descripcion_alter_tipo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normativa',
            options={'ordering': ['id'], 'verbose_name': 'Normativa', 'verbose_name_plural': 'Normativas'},
        ),
        migrations.AlterField(
            model_name='normativa',
            name='decreto',
            field=models.CharField(max_length=50, verbose_name='Decreto'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
    ]
