# Generated by Django 5.0.8 on 2024-08-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['id'], 'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
