# Generated by Django 5.1 on 2024-08-28 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_departamento_municipios_departamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='El número de celular debe contener solo dígitos.', regex='^\\d+$')], verbose_name='Número de celular'),
        ),
    ]
