# Generated by Django 5.1 on 2024-08-21 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_departamento', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Codigo departamento')),
                ('departamento', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamentos',
                'verbose_name_plural': 'Detalle departamentos',
                'db_table': 'departamentos',
                'ordering': ['id'],
            },
        ),
    ]
