# Generated by Django 5.1.1 on 2024-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_normativa_options_alter_normativa_decreto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
