# Generated by Django 5.0.6 on 2024-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_producto_imagen_prod_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='apellido',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ManyToManyField(blank=True, related_name='productos', to='app.tipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
    ]
