# Generated by Django 5.1.1 on 2024-09-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_compras_options_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
    ]
