# Generated by Django 5.0.6 on 2024-07-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tipo_apellido_producto_tipo_tipo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
