# Generated by Django 5.1 on 2024-08-21 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_departamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='departamento',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(default='Nombre por Defecto', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='codigo_departamento',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Codigo departamento'),
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_municipio', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Codigo municipio')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='municipio')),
                ('cod_departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamentos', to_field='codigo_departamento')),
            ],
            options={
                'verbose_name': 'Municipios',
                'verbose_name_plural': 'Detalle municipios',
                'db_table': 'municipios',
                'ordering': ['id'],
            },
        ),
    ]
