# Generated by Django 5.1 on 2024-08-28 21:27

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_persona_telefono_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(5), app.models.validate_nombre], verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='descripcion',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10), app.models.validate_nombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombre'),
        ),
    ]
