# Generated by Django 5.0.6 on 2024-07-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_pro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
