# Generated by Django 5.1 on 2024-08-28 21:38

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_categoria_descripcion_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombres'),
        ),
    ]
