# Generated by Django 5.1.1 on 2024-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cliente_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(verbose_name='Fecha de Compra'),
        ),
    ]
