# Generated by Django 5.1 on 2024-08-22 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_departamentos_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'ordering': ['id'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='codigo_departamento',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe ser de 2 dígitos numéricos.', regex='^\\d{2}$')], verbose_name='Código departamento'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='cod_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamentos', to_field='codigo_departamento', verbose_name='Código departamento'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='codigo_municipio',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código debe ser de 1 a 5 dígitos numéricos.', regex='^\\d{1,5}$')], verbose_name='Código municipio'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
    ]
