# Generated by Django 5.0.8 on 2024-08-06 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cliente_telefono_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='El número de documento debe contener solo dígitos.', regex='^\\d+$')], verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='El número de documento debe contener solo dígitos.', regex='^\\d+$')], verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(3176709994)]),
        ),
    ]
