# Generated by Django 5.1 on 2024-08-30 18:31

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_persona_apellidos_alter_persona_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(5), app.models.validate_nombre], verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='decreto',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Decreto'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='descripcion',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10), app.models.validate_nombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.CharField(max_length=20, unique=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), app.models.validate_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='num_factura',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
