# Generated by Django 5.1 on 2024-08-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_departamentos_options_alter_municipios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['id'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.municipios', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamentos', verbose_name='Departamento'),
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='ubicacion',
        ),
    ]
