# Generated by Django 5.1 on 2024-08-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_categoria_descripcion_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.RenameField(
            model_name='municipios',
            old_name='departamento_id',
            new_name='departamento',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
