# Generated by Django 5.1 on 2024-08-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ubicacion_options_remove_ubicacion_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipios',
            old_name='cod_departamento',
            new_name='cod_departamento_id',
        ),
    ]
