# Generated by Django 5.1 on 2024-08-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_detallecompra_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='persona',
        ),
    ]
