# Generated by Django 5.1 on 2024-08-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_cod_departamento_municipios_cod_departamento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipios',
            name='codigo_municipio',
        ),
    ]
