# Generated by Django 5.0.7 on 2024-07-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_proveedor_nit_proveedor_razon_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cod_postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='Ubicacion'),
        ),
    ]
