# Generated by Django 5.1 on 2024-08-23 18:38

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_municipios_codigo_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='codigo_departamento',
            field=models.PositiveIntegerField(unique=True, validators=[app.models.validate_codigo_departamento], verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=50, validators=[app.models.validate_nombre], verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='cod_departamento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamentos', to_field='codigo_departamento', verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='nombre',
            field=models.CharField(max_length=50, validators=[app.models.validate_nombre], verbose_name='Municipio'),
        ),
    ]
