# Generated by Django 5.0.7 on 2024-07-12 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_proveedor_nit_proveedor_razon_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nit',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cod_postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razon Social'),
        ),
    ]
