# Generated by Django 5.1 on 2024-08-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_departamentos_codigo_departamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipios',
            old_name='cod_departamento_id',
            new_name='cod_departamento',
        ),
    ]
