# Generated by Django 5.0.7 on 2024-07-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_proveedor_cod_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento'),
        ),
    ]
