# Generated by Django 5.1 on 2024-08-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_cod_departamento_id_municipios_cod_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='app.departamentos', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='app.municipios', verbose_name='Municipio'),
        ),
    ]
