# Generated by Django 5.0.7 on 2024-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_proveedor_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razon Social'),
        ),
    ]
