# Generated by Django 5.0.7 on 2024-07-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_proveedor_numero_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nit',
        ),
    ]
