# Generated by Django 5.0.7 on 2024-07-25 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_categoria_descripcion_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
    ]
