# Generated by Django 5.0.7 on 2024-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_tipo_descripcion_alter_tipo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['id'], 'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicacion'},
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
