# Generated by Django 5.0.7 on 2024-07-25 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_ubicacion_options_alter_ubicacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.CharField(choices=[('1', 'Amazonas'), ('2', 'Antioquia'), ('3', 'Arauca'), ('4', 'Atlántico'), ('5', 'Bolívar'), ('6', 'Boyacá'), ('7', 'Caldas'), ('8', 'Caquetá'), ('9', 'Casanare'), ('10', 'Cauca'), ('11', 'Cesar'), ('12', 'Chocó'), ('13', 'Córdoba'), ('14', 'Cundinamarca'), ('15', 'Güainia'), ('16', 'Guaviare'), ('17', 'Huila'), ('18', 'La Guajira'), ('19', 'Magdalena'), ('20', 'Meta'), ('21', 'Nariño'), ('22', 'Norte de Santander'), ('23', 'Putumayo'), ('24', 'Quindío'), ('25', 'Risaralda'), ('26', 'San Andrés y Providencia'), ('27', 'Santander'), ('28', 'Sucre'), ('29', 'Tolima'), ('30', 'Valle del Cauca'), ('31', 'Vaupés'), ('32', 'Vichada')], default='1', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Departamento'),
        ),
    ]
