# Generated by Django 5.0.7 on 2024-07-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categ',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.venta', verbose_name='Venta'),
        ),
    ]
