# Generated by Django 5.0.7 on 2024-07-25 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_categ_producto_categoria_producto_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario Normal')], verbose_name='Rol')),
                ('nombres', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('usuario', models.CharField(max_length=150, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
