# Generated by Django 5.0.7 on 2024-07-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_persona_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fecha_ingreso',
            new_name='fecha_salida',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='iva',
            new_name='impuestos',
        ),
        migrations.AddField(
            model_name='venta',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
    ]
