# Generated by Django 5.0.7 on 2024-07-25 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_fecha_ingreso_venta_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(8)], verbose_name='Numero de Documento'),
        ),
    ]
