# Generated by Django 5.0.7 on 2024-07-25 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='prod',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetalleVenta',
        ),
    ]
