# Generated by Django 5.0.7 on 2024-07-25 21:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='fk_venta',
            new_name='venta',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_salida',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total'),
        ),
    ]
