# Generated by Django 5.0.7 on 2024-07-25 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_fk_venta_detalleventa_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo'),
        ),
    ]
