# Generated by Django 5.0.7 on 2024-07-25 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_proveedor_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(8)], verbose_name='Numero de Documento'),
        ),
    ]
