# Generated by Django 5.0.7 on 2024-07-25 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_proveedor_apellidos_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='decreto',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Decreto'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='descripcion',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='normativa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
