# Generated by Django 5.0.7 on 2024-07-25 21:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_normativa_decreto_alter_normativa_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio Unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio Total')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Ingreso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compra',
                'ordering': ['id'],
            },
        ),
    ]
